### ISSUE TITLE
Demo engine getting faster on every refresh

### ISSUE THREAD

**Issue by abides** [JohnnyDevNull/ng-three-template#12]
Hi,

I will try to explain this weird problem. Did you ever used angular router?

When i change the route and come back to engine component page the animation getting faster and faster everytime i change the path and come back. When i change the url manually its reset its speed.

Any idea what could be the reason?

Best regards

**Comment by abides** [comment]
https://user-images.githubusercontent.com/726511/146611835-0952db42-b234-4b98-b52b-ee2447b1cd50.mp4

after couple of routes and come back to engine component, i achieve this speed :)

**Comment by abides** [comment]
It seems stopping animation with cancelAnimationFrame on service does not enough to cleanup objects in memory. Actually its not called at all on routing change. I added call to component onNgDestroy but that is also not enough. When routing changes, animation still ticking behind and after couple of fast route changes (15-20) its start to give console warning "WARNING: Too many active WebGL contexts. Oldest context will be lost."

**Comment by abides** [comment]
I'm not sure its the fastest way to solve this but creating canvas element using renderer2 and adding to dom then remove it onDestroy looks like solve the problem for me. Still open for suggestions.

**Comment by JohnnyDevNull** [comment]
Hi @abides, sorry for the late answer, i was the last weeks not really active on my public dev repos.

Do you have a working [StackBlitz](https://stackblitz.com/) example?
When not please setup one, then i'am going to take a look at.

**Comment by JohnnyDevNull** [comment]
@abides maybe this cleanup in the ngOnDestroy within the service could solve your problem, if not feel free to reopen the issue:

```ts
  public ngOnDestroy(): void {
    if (this.frameId != null) {
      cancelAnimationFrame(this.frameId);
    }
    if (this.renderer != null) {
      this.renderer.dispose();
      this.renderer = null;
      this.canvas = null;
    }
  }
```
