### ISSUE TITLE
Get size of canvas not window in resize

### ISSUE THREAD

**Issue by JTray123** [JohnnyDevNull/ng-three-template#8]
Hope someone can help

I need to get the size of the canvas  not overall window. Doesn't matter what I try it stays fixed at 300 which I believe is the defaults. 

So how would I rewrite this function to use the size of the canvas passed in as opposed to the overall window size

```
`public resize(): void {
    const width = window.innerWidth;
    const height = window.innerHeight;

    this.cameraNew.aspect = width / height;
    this.cameraNew.updateProjectionMatrix();

    this.rendererNew.setSize( width, height );
  }`
```

**Comment by blakazulu** [comment]
Haven't tested it yet but try this:

change the animate() to this:

    public animate(elRef?: ElementRef): void {
    // We have to run this outside angular zones,
    // because it could trigger heavy changeDetection cycles.
    this.ngZone.runOutsideAngular(() => {
      if (document.readyState !== 'loading') {
        this.render();
      } else {
        window.addEventListener('DOMContentLoaded', () => {
          this.render();
        });
      }

      window.addEventListener('resize', () => {
        this.resize(elRef);
      });
    });
    }


change the resize() to this:

    public resize(elRef?: ElementRef): void {
    const width = elRef ? elRef.nativeElement.getBoundingClientRect().width : window.innerWidth;
    const height = elRef ? elRef.nativeElement.getBoundingClientRect().height : window.innerHeight;

    this.camera.aspect = width / height;
    this.camera.updateProjectionMatrix();

    this.renderer.setSize(width, height);
    }

change the ngOnInit inside engine.component.ts to this:

    public ngOnInit(): void {
    this.engServ.createScene(this.rendererCanvas);
    this.engServ.animate(this.rendererCanvas);
    }


let me know if it worked.
